apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # The namespace where the role will be applied
  name: deployer-role # Name of the role
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets" ]
  verbs: [ "*" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments", "daemonsets", "replicasets", "statefulsets" ]
  verbs: [ "*" ]
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: [ "*" ]
