apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: {{ .Values.appImage.replicaCount }}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: app
spec:
  type: {{ .Values.appService.type }}
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.port }}
  selector:
    app: app