apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-role-binding # Name of the binding
  namespace: default # The namespace where the binding will be applied
subjects:
- kind: ServiceAccount
  name: deployer # The service account you want to bind the role to
  namespace: default # The namespace of the service account
roleRef:
  kind: Role
  name: deployer-role # The name of the role being bound
  apiGroup: rbac.authorization.k8s.io
