appImage:
  replicaCount: 1
  repository: yuvalbenjamin/my-app
  tag: latest
  pullPolicy: IfNotPresent

appService:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
