appImage:
  replicaCount: 1
  repository: yuvalbenjamin/my-public-ip
  tag: latest
  pullPolicy: IfNotPresent

appService:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
